### ISSUE TITLE
Additional login providers

### ISSUE THREAD

**Issue by alexwaeseperlman** [alexwaeseperlman/Pokerbots#14]
I looked a bit at [Amazon Cognito](https://aws.amazon.com/cognito/). I think we should use this instead of manually implementing OAuth for every provider. It will also make other features easier to implement (like [direct upload to S3](https://docs.aws.amazon.com/AmazonS3/latest/userguide/UsingHTTPPOST.html))

**Comment by alexwaeseperlman** [comment]
I think we should give up on the idea of using school accounts for this and instead make it completely open. This means that aws cognito should work. We can use it for username/password auth and only a few external providers.

**Comment by ssantoshp** [comment]
Is your last comment still to relevant to what you want to do? No school email?
