### ISSUE TITLE
Minor Documentation Problems

### ISSUE THREAD

**Issue by rt-kill** [alexwaeseperlman/Pokerbots#73]
I didn't want to immediately open a PR because I don't really know where this project stands or what is going to be changed, but after looking at a public game log it seems there may be some inconsistencies with the IO documentation, and the simulator.

It is not mentioned that lines will start with a character such as `P`, `C`, or `S`.

The relative chip counts appear after the cards are given, in the same line as the pot state. 

There is an unmentioned output character `X`? I'm assuming this means check.

Whenever new cards are printed (flop, turn, river) all previous cards are also printed (not just the new one).

A smaller independent point would be to have all the IO in a single document instead of having the Betting Rounds IO in `Game Rules`, and all other general IO in `Building a Bot`. Would it also be worth it to mention some basic poker rules and how 
 winners are decided?

If this is a problem with the documentation as opposed to the simulation, I'd be happy to open a PR updating it

**Comment by alexwaeseperlman** [comment]
Thanks for noticing these. They sound like issues with documentation rather than the engine. We are still working on the schema so I don't want to spend too much time on documentation right now, but if you have questions about developing a bot we should discuss on Discord.

**Comment by alexwaeseperlman** [comment]
Hey I know it's been a while but I just updated the communication schema and the [building a bot](https://docs.upac.dev/bot_dev.html) section of the docs. If you have some time could you take another look and try writing a bot based on the guide?

**Comment by rt-kill** [comment]
Updates look great 🦾 -- I wrote some bots, and they seem to be working!

The only nitpick would be that in the `game_rules` route the syntax `R<N>` is used instead of `R(N)`. Personally I prefer `<N>` instead of `(N)`, but it might make things hard on the eyes when used everywhere, so I'm not sure.

Closing

**Comment by alexwaeseperlman** [comment]
Thanks again for looking at this. It's super helpful
